import { SidebarDemo } from "@/components/ui/left-sidebar";
import { ThemeProvider } from "@/context/ThemeContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ThemeProvider>
        <div className="flex flex-row">
          <div>
            <SidebarDemo />
          </div>
          <div className="w-full"> {children}</div>
        </div>
      </ThemeProvider>
    </>
  );
}
