import { SidebarDemo } from "@/components/ui/left-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ThemeProvider } from "@/context/ThemeContext";
import { UserProvider } from "@/context/userdataContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <UserProvider>

        <div className="flex flex-row">
          <div>
<SidebarProvider>
            <SidebarDemo />
</SidebarProvider>
          </div>
          <div className="w-full"> {children}</div>
        </div>
    </UserProvider>
    </>
  );
}
